### ISSUE TITLE
Backpropagation doesn't work when a input-value is 0

### ISSUE THREAD

**Issue by Mafii** [Mafii/BackpropagationSharp#1]
Devided by 0 error occures if using decimal, NaN is the result when using float/double.

**Comment by Mafii** [comment]
@SirRade any ideas what to do? see: https://github.com/Mafii/BackpropagationSharp/blob/master/BackpropagationSharp/Model/BackpropagationOperator.cs#L69

**Comment by Mafii** [comment]
Fix: Replace all divisions by multiplication by the reciprocal

**Comment by SirRade** [comment]
Perhaps you will find something useful here?  https://github.com/SirRade/simple_backpropagation/blob/master/Backpropagation/main.cpp  
Note that this changes all the divisions to multiplications

**Comment by Mafii** [comment]
Resolved with ae635ebd69d3da62d1beea19800ae5f789878bb7
